dev-deployment:
  variables:
    GIT_STRATEGY: fetch
  script:
    - bash ~/gitlab/NextJS/nextjs-projectdeploy-yarn-v1.sh
  environment:
    name: Development
    url: https://unilabs-ui.dedicateddevelopers.us/
  tags:
    - node-nextjs
  only:
    - dev
