version: "3"

services:
  #React Nextjs Node Service

  node:
    image: webskittersdocker/nvmnode20:latest

    container_name: unilabs-ui-NextJS

    restart: unless-stopped

    working_dir: /home/wtsadmin/myapp

    volumes:
      - ./:/home/wtsadmin/myapp

    ports:
      - "14342:14342"
    command: >
      sh -c "yarn start"

#Docker Networks

networks:
  default:
    external:
      name: webskitters
